### ISSUE TITLE
But how to implement?

### ISSUE THREAD

**Issue by oueryemchi** [tpmdud/dodecagondiv#4]
Hi there,it seems interesting but how to implement? let's say I have a wordpress user avatar that I want to shape as an hexagon?

Thanks in advance
A

**Comment by tpmdud** [comment]
you need to some how add jquery, my plugin and my css in your head tag, i dont know how to do this in wordpress but in contao that is very easy. Some where after you added thouse 3 tags, you need to initiate the plugin
like this

``` html
<head>
   <link href="tpmdodecagondiv.css" rel="stylesheet" />
   <script src='http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js' type='text/javascript'></script>
   <script src='tpmdodecagondiv.js' type='text/javascript'></script>
    <script>
    $(function(){
          $('.tpmdodecagondiv').tpmdodecagondiv();
    });
    </script>
</head>
```

in a script tag '.tpmdodecagondiv' (the first, not the seccond!!!) can be replaced by a class you want to use to apply the hexagon / dodecagon later in the code.

by default the TPMDIV has a with of 200px and has 12 corners --> so it is a dodecagon if you want to use hexagons or custom with's just apply them to the code like this:

``` html
<script>
$(function(){
    $('.tpmdodecagondiv').tpmdodecagondiv({
        width : '100px',    
        corners : 6, 
    });
});
</script>
```

So now you can add as many hexagon img to your site as you want just add <b>class="tpmdodecagondiv"</b> to your img and i'll create a hexagon for you.

hope that helped you, if not feel free to send a email to me, like i said im to dumb to add code in a github comment.

**Comment by oueryemchi** [comment]
Thanks! much appreciated!

**Comment by tpmdud** [comment]
if it worked and you are planning to implement it in your site, make sure to send me a link ;)
and if not feedback is anyway appreciated.

**Comment by oueryemchi** [comment]
Thanks man! it works, one more question please..if I want to give a border to the hexagone, let's say :

``` css
border: 4px solid #ffffff;
```

How to do that?

**Comment by tpmdud** [comment]
hello again
at the moment you can't BUT
I'll upload a new today or tomorrow i just have to test some stuff, then you can do a:

``` html
<div class="dodecagon2">
   <img class="dodecagon1">
   </img>
<div>
```

So you create a hexagon in a hexagon. The first for the "border", the seccond for the image. (of curse you have to make the first one like 8px wider and add some magin to the seccond, you can do this by add the class atribute to the initiation script, if you don't know what i mean, the demo file is using this)

but like i said, the current uploaded version doesn't support divs jet.
So you have to w8 for tomorrow.
